[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "#auto"
  port = 8890
  publish = "dist"
  functions = "netlify/functions"
  # Activer l'environnement local
  autoLaunch = true
  targetPort = 5173

# Variables d'environnement pour le développement local
# Ces valeurs seront remplacées par les variables d'environnement définies dans l'interface Netlify
[build.environment]
  VITE_ADMIN_USERNAME = "admin_placeholder"
  VITE_ADMIN_PASSWORD = "password_placeholder"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
