[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "#auto"
  port = 8888
  publish = "dist"
  functions = "netlify/functions"
  # Activer l'environnement local
  autoLaunch = true
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
