[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "#auto"
  port = 8890
  publish = "dist"
  functions = "netlify/functions"
  # Activer l'environnement local
  autoLaunch = true
  targetPort = 5173

# Variables d'environnement pour le développement local
# Ces valeurs seront remplacées par les variables d'environnement définies dans l'interface Netlify
# Ne pas mettre de valeurs réelles ici, utilisez l'interface Netlify
[build.environment]
  # Ces valeurs sont des placeholders et doivent être remplacées dans l'interface Netlify
 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
